version: '3'
services:
  img-gallery:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - img-gallery-net
    ports:
      - '8080:8080'
    environment:
      - MONGO_HOST=img-gal-mongo
    expose:
      - 8080
    depends_on:
      - img-gal-mongo
    logging:
      driver: json-file
    restart: always
  img-gal-mongo:
    image: mongo:latest
    container_name: img-gal-mongo
    networks:
      - img-gallery-net
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=db-root
      - MONGO_INITDB_ROOT_PASSWORD=notroot_pswd
      - MONGO_INITDB_DATABASE=img-gallery
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - img-gal-db-volume:/data/db
    restart: always
volumes:
  img-gal-db-volume:
networks:
  img-gallery-net:
    driver: bridge
